### ISSUE TITLE
Fluid Interface

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#228]
Ensure that this works with External Storage.

Should import instantly, just like exporting.

Is this still necessary, with grids supporting multiple resource types in #241? Should the interface be unified as well?

**Comment by bulldog98** [comment]
> Is this still necessary, with grids supporting multiple resource types in https://github.com/refinedmods/refinedstorage2/issues/241? Should the interface be unified as well?

that seems reasonable, but we should question, if a unified item and fluid output is to much. Maybe we should limit the interface to output/input one type (fluid xor item).

**Comment by raoulvdberge** [comment]
> that seems reasonable, but we should question, if a unified item and fluid output is to much. Maybe we should limit the interface to output/input one type (fluid xor item).

This is a good point. However, it's important to note that external storage supports multiple resource types at once as well at the moment.

The biggest problem about combining fluids in the regular interface is that the container menu starts doing a lot of stuff. The slot type will change dynamically (extracting a bucket for example from a dynamic slot will be difficult, while the fluid interace is specialized for this), a fluid handler needs to be exposed dynamically as well, etc.

Maybe I'm making it bigger in my head than necessary though.

**Comment by jonatjano** [comment]
Having a unified interface is something you plan to do (if I understand correctly [#167 - Duality Block](https://github.com/refinedmods/refinedstorage2/issues/167))
Doing it from the start may make the follow up easier than doing separate interface now and a unified interface later, with the changes which accompanies it

**Comment by raoulvdberge** [comment]
Unified interface is a possibility.
#167 is a stop gap solution while the unified interface is being considered. It's a separate block that has nothing to do with interfaces.

**Comment by raoulvdberge** [comment]
So the plan is to go for a unified interface.
Steps:
- [x] Generify "resource filter slots" to resource slots - implemented as part of #407
- [x] Allow item interactions with such a resource slot - implemented as part of #407
- [x] Support importing/exporting any resource in the interface (w/ the resource slots) - implemented as part of #410
- [x] Expose an item or fluid handler dynamically on the block - implemented as part of #411
- [x] Remove #167 from the roadmap. It won't be necessary anymore to ease automation with crafters, since the interface can accept multiple resource types on 1 side as well.
