### ISSUE TITLE
Add gametests

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#248]
# TODO

Gametests are located here: https://github.com/refinedmods/refinedstorage2/tree/develop/refinedstorage-neoforge/src/test/java/com/refinedmods/refinedstorage/common

To contribute: import the refined storage repo into in IntelliJ and run the "Refinedstorage-platform-forge: Client" run config.

If you want to pick any of these up, [let us know on Discord](https://discordapp.com/invite/VYzsydb) on the #refinedstorage2 channel.

## v2.0.0-milestone.1

- [x] Fluid Storage Blocks
- [x] Storage Blocks
- [x] Disk Drive / Storage Disk / Fluid Storage Disk
- [x] Controller / Creative Controller
  - This mainly for energy usage? 

## v2.0.0-milestone.2

- [x] Regulator Upgrade
  - For exporters and importers. 
- [x] Constructor
- [x] Silk Touch Upgrade
- [x] Destructor
- [x] Detector
- [ ] Colored cable connection rules (#323)
- [x] Interface
- [x] External Storage
- [ ] Interface + External Storage combination
- [x] Exporter
- [x] Stack Upgrade
- [x] Importer

## v2.0.0-milestone.3

- [x] Relay
  - Pass-through mode, non pass-trough mode (subnetworks)
- [ ] Void excess option on the storages (first do all the storages)
- [ ] Network Transmitter + Network Receiver + Network Card (same dimension)
- [x] Disk Interface (formerly known as "Disk Manipulator")
 
## v2.0.0-milestone.4

- [ ] Ability to differentiate between insert/extract storage priorities (on the storages and on the Relay)
- [x] Autocrafting
  - [x] Processing
  - [x] Regular patterns
  - [x] Combination of processing and regular patterns
  - [x] Autocrafter chaining
- [ ] Autocrafting with the Relay (subnetworks)
- [ ] Autocrafting Upgrade

**Comment by raoulvdberge** [comment]
I've a skeleton ready for this, I'll add it soon.
