### ISSUE TITLE
Autocrafting engine

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#612]
- [x] Should have a button in the crafting preview that fills out the maximum amount currently craftable.
- [x] Should allow multiple patterns with the same output. See RS1 issue: https://github.com/refinedmods/refinedstorage/issues/2675
- [x] Should send a notification if a task is finished, but have it be a config option and checkbox from the preview window.
  - **Art necessary:** The toast could use a nice texture. See `textures/gui/sprites/autocrafting_task_completed_toast.png`

 
## Impact to the Autocrafting Monitor
- [x] Should show the machine name for processing patterns.
- [x] Should not allow cancelling tasks if there is not enough space in the network left: https://github.com/refinedmods/refinedstorage/issues/3349

## Impact to the Pattern Grid
- [x] Pattern Grid transfer should also look for autocraftable items and patterns in inventory: https://github.com/refinedmods/refinedstorage/pull/2975#issuecomment-857858655 (see RS 1) 

## Impact to the Relay
- [x] Ensures that it works with subnetworks (#108 and #80)
  - Expose autocrafting and start a crafting task in the source network.

**Comment by HallowedJam** [comment]
Is there now or will there be the ability to infinitely reuse non-consumed items in an autocrafter? ie: Pestle & mortar + petal in Botania, currently if I wanted to do that recipe 64 times I would need 64 Pestle & mortars even though it doesn't have durability and will never break.

**Comment by Nodrance** [comment]
That's a highly requested feature, the current answer is "maybe, i'll consider it once i have autocrafting for rs2 working"
